# Generated by Django 3.0.2 on 2020-01-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathermodel',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
